name: pypi
on: [push]
jobs:
  test_build_run:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
      - name: docker login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}
      - name: Run tests
        run : |
          pip install pytest
          pytest
      - name: build docker image
        run: 
          docker build -t test .     
      - name: run docker image
        run: docker run test
      - name: docker tag
        run:  docker tag test:latest papiskoby/pipy:pipeline
      - name: docker push
        run:  docker push papiskoby/pipy:pipeline  